spring.datasource.url=jdbc:postgresql://db.vxtrxbytdhstkooepnda.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=sWQGRx2CYW8I0KOF
resend.api.key=re_CBfhddaa_9KX87N22zqA42KmrWKN4x8k4
spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.secret=47d68f59ef61038b0a223b19913a61c4