spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.secret=b4205196fe710feee0b841206b377441


spring.datasource.username=postgres.vxtrxbytdhstkooepnda
spring.datasource.password=sWQGRx2CYW8I0KOF
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com/postgres?prepareThreshold=0